### ISSUE TITLE
Swift 2.0 support

### ISSUE THREAD

**Issue by KyleMay** [Isuru-Nanayakkara/Reach#10]
Doesn't compile with Swift 2.0

**Comment by danwallacenz** [comment]
I've submitted a pull request for this issue.

**Comment by bryan1anderson** [comment]
I'd like to know if Swift 2 is working yet

**Comment by KyleMay** [comment]
Given that the last commit was 7 months ago (i.e. not after this issue was created), I'd say no. But if you clone @danwallacenz's fork on branch `swift2-with-autodetect` it will work.

**Comment by danwallacenz** [comment]
Yes. Should be OK.
Dan.

**Comment by AndrewAKing** [comment]
@Isuru-Nanayakkara Do you plan to update for 2.0 so cocoa pods can update?

**Comment by vigyanhoon** [comment]
Does this work on Swift 2.0 Xcode 7?

**Comment by AndrewAKing** [comment]
@vigyanhoon yes

**Comment by thejourneydude** [comment]
Just tested @danwallacenz branch on XCode 7 GM and received the following error on this line of code.

`SCNetworkReachabilityGetFlags(defaultRouteReachability, &flags) == 0 `

`Binary operator == cannot be applied to operands of type Bool and Int`

**Comment by AndrewAKing** [comment]
@thejourneydude I submitted a pull request to his branch with the fix but it seems it's not been acted upon yet.

All you need to do is change it to false instead of 0.

`SCNetworkReachabilityGetFlags(defaultRouteReachability, &flags) == false`

**Comment by thejourneydude** [comment]
Yep, just forked my own version. If anyone is interested while waiting for the merge, here is what I set up for a fix.

    pod 'IJReachability', git: 'https://github.com/thejourneydude/IJReachability.git', branch: 'swift2-with-autodetect'

**Comment by loucimj** [comment]
@thejourneydude thanks!!! you saved my life :)

**Comment by jaysonng** [comment]
Anyone get these SCNetworkReachabilityCreateWithAddress "ambiguous use of init()" error in the XCode 7.0?
![screen shot 2015-09-19 at 4 57 46 pm](https://cloud.githubusercontent.com/assets/440445/9975461/98bb47de-5eef-11e5-98a3-e37f41e80e44.png)

**Comment by Jamal1337** [comment]
Yes I got the same issues but was able to fix it with the help of:
http://stackoverflow.com/questions/25623272/how-to-use-scnetworkreachability-in-swift

**Comment by jaysonng** [comment]
@Jamal1337 thank you! got most of them fixed but what did you do with the isWWAN section?

**Comment by jaysonng** [comment]
and is there a fork somewhere that has this working?

**Comment by Jamal1337** [comment]
Here, I forked my version. It works for me with Swift 2.0 and Xcode 7:
`pod 'IJReachability', git: 'https://github.com/Jamal1337/IJReachability.git', branch: 'master'`

**Comment by jaysonng** [comment]
thanks you @Jamal1337 !

**Comment by confile** [comment]
+1

**Comment by felipesabino** [comment]
@Jamal1337 Can you add a PR for that fix?

**Comment by Jamal1337** [comment]
@felipesabino yes I just did

**Comment by daliso** [comment]
Thanks Jamal!
