### ISSUE TITLE
Swift 3 version ?

### ISSUE THREAD

**Issue by sebastienboulogne** [Isuru-Nanayakkara/Reach#19]
Hi, your class seems to be simple and easy to use but unfortunately don't work on my swift 3 project :(

Do you plan to upgrade it ?

Thx ;)

**Comment by Isuru-Nanayakkara** [comment]
Hi,

I only installed Xcode 8 a few days ago. Getting the hang of the new syntax. I will update the class ASAP.

**Comment by Isuru-Nanayakkara** [comment]
The code is updated to Swift 3 now. Please check the `Reach-swift3.0` directory in the repo.
